export const ADDTODO_ITEM = "ADDTODO_ITEM";
export const UPDATETODO_ITEMS = "UPDATETODO_ITEMS";
export const COMPLETE_TODO_ITEM = "COMPLETE_TODO_ITEM";
export const DELETETODO_ITEM = "DELETETODO_ITEM";
export const LOAD_EXISTING_TODOS = "LOAD_EXISTING_TODOS";
export const RESET_DONE_ITEM = "RESET_DONE_ITEM";

